{% set name = "cuda-nvprof" %}
{% set version = "12.6.68" %}
{% set cuda_version = "12.6" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprof/{{ platform }}/cuda_nvprof-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: a0bd653f2876a8ba09c3568ee0732e3bef5d44fb8d36a48d77f2ce19b2eac0c2  # [linux64]
  sha256: 76a9030891a902c2de5bf375e8cdc9a4702fa1d80fddcf3f7c04e8e3105d47a0  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or aarch64 or ppc64le]
  missing_dso_whitelist:
    # This is a driver file, might be able to use cuda-compat to remove this
    - '*/libcuda.so.1'  # [linux]
    - '*/libgcc_s.so.1'  # [linux]
    - '*/libstdc++.so.6'  # [ppc64le]
    - '*/nvcuda.dll'    # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - patchelf <0.18.0  # [linux]
  host:
    - cuda-version {{ cuda_version }}
    - cuda-cupti
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-cupti

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/bin/nvprof                                                                                            # [linux]
    - test -f $PREFIX/lib/pkgconfig/cuinj64*.pc                                                                             # [linux]
    - test -f $PREFIX/lib/pkgconfig/accinj64*.pc                                                                            # [linux]
    - test -L $PREFIX/lib/libaccinj64.so                                                                                    # [linux]
    - test -L $PREFIX/lib/libaccinj64.so.{{ version.split(".")[0] }}.{{ version.split(".")[1] }}                            # [linux]
    - test -L $PREFIX/lib/libaccinj64.so.{{ version }}                                                                      # [linux]
    - test -L $PREFIX/lib/libcuinj64.so                                                                                     # [linux]
    - test -L $PREFIX/lib/libcuinj64.so.{{ version.split(".")[0] }}.{{ version.split(".")[1] }}                             # [linux]
    - test -L $PREFIX/lib/libcuinj64.so.{{ version }}                                                                       # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libaccinj64.so                                                          # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libaccinj64.so.{{ version.split(".")[0] }}.{{ version.split(".")[1] }}  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/libaccinj64.so.{{ version }}                                            # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libcuinj64.so                                                           # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libcuinj64.so.{{ version.split(".")[0] }}.{{ version.split(".")[1] }}   # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/libcuinj64.so.{{ version }}                                             # [linux]
    - bash test-rpath.sh                                                                                                    # [linux]
    - if not exist %LIBRARY_BIN%\nvprof.exe exit 1     # [win]
    - if not exist %LIBRARY_BIN%\cuinj64_*.dll exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Tool for collecting and viewing CUDA application profiling data
  description: |
    Tool for collecting and viewing CUDA application profiling data from
    the command-line.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
